2025-02-27 23:04:35,557 - INFO - Starting receiving server...
2025-02-27 23:04:35,557 - INFO - Socket receive buffer size set to: 0.41 MB
2025-02-27 23:04:35,557 - INFO - Server listening on 192.168.1.3:9000
2025-02-27 23:04:35,557 - INFO - Waiting for connection...
2025-02-27 23:04:36,681 - INFO - Got a connection from ('192.168.1.3', 35310)
2025-02-27 23:04:36,681 - INFO - Received 0.03MB in 1 chunks. Transfer rate: 258.26MB/s
2025-02-27 23:04:36,682 - INFO - Received 0.34MB in 2 chunks. Transfer rate: 623.85MB/s
2025-02-27 23:04:36,682 - INFO - Received 0.37MB in 3 chunks. Transfer rate: 542.68MB/s
2025-02-27 23:04:36,682 - INFO - Received 0.69MB in 4 chunks. Transfer rate: 539.43MB/s
2025-02-27 23:04:36,683 - INFO - Received 0.94MB in 5 chunks. Transfer rate: 573.11MB/s
2025-02-27 23:04:36,689 - INFO - Connection closed. Received 6.55MB in 28 chunks. Average speed: 796.48MB/s
2025-02-27 23:04:36,693 - INFO - Data decoded successfully, length: 6872654
2025-02-27 23:04:36,693 - INFO - Attempting to parse JSON data
2025-02-27 23:04:36,832 - INFO - JSON parsed successfully. DataFrame shape: (5843, 55)
2025-02-27 23:04:36,904 - INFO - Data saved to received/received_data_20250227_230436.csv
2025-02-27 23:04:36,904 - INFO - Waiting for connection...
2025-02-27 23:09:17,879 - INFO - Starting receiving server...
2025-02-27 23:09:17,880 - INFO - Socket receive buffer size set to: 0.41 MB
2025-02-27 23:09:17,880 - ERROR - Server error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mohamed/Desktop/workstation/FL-CML-Pipeline/data/receiving_data.py", line 34, in start_server
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
2025-02-27 23:09:17,880 - INFO - Server socket closed
2025-02-27 23:09:18,875 - INFO - Got a connection from ('192.168.1.3', 39330)
2025-02-27 23:09:18,875 - INFO - Received 0.31MB in 1 chunks. Transfer rate: 3676.36MB/s
2025-02-27 23:09:18,876 - INFO - Received 0.37MB in 2 chunks. Transfer rate: 2118.58MB/s
2025-02-27 23:09:18,876 - INFO - Received 0.44MB in 3 chunks. Transfer rate: 1596.49MB/s
2025-02-27 23:09:18,876 - INFO - Received 0.69MB in 4 chunks. Transfer rate: 1617.03MB/s
2025-02-27 23:09:18,876 - INFO - Received 0.94MB in 5 chunks. Transfer rate: 1569.57MB/s
2025-02-27 23:09:18,876 - INFO - Connection closed. Received 1.75MB in 9 chunks. Average speed: 1657.44MB/s
2025-02-27 23:09:18,877 - INFO - Data decoded successfully, length: 1830064
2025-02-27 23:09:18,877 - INFO - Attempting to parse JSON data
2025-02-27 23:09:18,917 - INFO - JSON parsed successfully. DataFrame shape: (1580, 55)
2025-02-27 23:09:18,938 - INFO - Data saved to received/received_data_20250227_230918.csv
2025-02-27 23:09:18,938 - INFO - Waiting for connection...
2025-02-27 23:33:00,174 - INFO - Starting receiving server...
2025-02-27 23:33:00,174 - INFO - Socket receive buffer size set to: 0.41 MB
2025-02-27 23:33:00,174 - ERROR - Server error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mohamed/Desktop/workstation/FL-CML-Pipeline/data/receiving_data.py", line 34, in start_server
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
2025-02-27 23:33:00,174 - INFO - Server socket closed
2025-02-27 23:33:01,278 - INFO - Got a connection from ('192.168.1.3', 51878)
2025-02-27 23:33:01,278 - INFO - Received 0.06MB in 1 chunks. Transfer rate: 428.07MB/s
2025-02-27 23:33:01,278 - INFO - Received 0.34MB in 2 chunks. Transfer rate: 1054.42MB/s
2025-02-27 23:33:01,278 - INFO - Received 0.37MB in 3 chunks. Transfer rate: 914.61MB/s
2025-02-27 23:33:01,278 - INFO - Received 0.44MB in 4 chunks. Transfer rate: 758.12MB/s
2025-02-27 23:33:01,279 - INFO - Received 0.62MB in 5 chunks. Transfer rate: 876.28MB/s
2025-02-27 23:33:01,279 - INFO - Received 0.87MB in 6 chunks. Transfer rate: 1011.08MB/s
2025-02-27 23:33:01,281 - INFO - Connection closed. Received 6.76MB in 40 chunks. Average speed: 2394.67MB/s
2025-02-27 23:33:01,282 - INFO - Data decoded successfully, length: 7086029
2025-02-27 23:33:01,283 - INFO - Attempting to parse JSON data
2025-02-27 23:33:01,419 - INFO - JSON parsed successfully. DataFrame shape: (6029, 56)
2025-02-27 23:33:01,487 - INFO - Data saved to received/received_data_20250227_233301.csv
2025-02-27 23:33:01,487 - INFO - Waiting for connection...
2025-02-27 23:48:02,334 - INFO - Starting receiving server...
2025-02-27 23:48:02,334 - INFO - Socket receive buffer size set to: 0.41 MB
2025-02-27 23:48:02,334 - ERROR - Server error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mohamed/Desktop/workstation/FL-CML-Pipeline/data/receiving_data.py", line 34, in start_server
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
2025-02-27 23:48:02,334 - INFO - Server socket closed
2025-02-27 23:48:03,450 - INFO - Got a connection from ('192.168.1.3', 58778)
2025-02-27 23:48:03,453 - INFO - Received 0.03MB in 1 chunks. Transfer rate: 11.07MB/s
2025-02-27 23:48:03,453 - INFO - Received 0.34MB in 2 chunks. Transfer rate: 115.00MB/s
2025-02-27 23:48:03,454 - INFO - Received 0.37MB in 3 chunks. Transfer rate: 121.20MB/s
2025-02-27 23:48:03,454 - INFO - Received 0.44MB in 4 chunks. Transfer rate: 135.47MB/s
2025-02-27 23:48:03,454 - INFO - Received 0.69MB in 5 chunks. Transfer rate: 203.02MB/s
2025-02-27 23:48:03,454 - INFO - Received 0.94MB in 6 chunks. Transfer rate: 261.16MB/s
2025-02-27 23:48:03,457 - INFO - Connection closed. Received 8.10MB in 64 chunks. Average speed: 1241.56MB/s
2025-02-27 23:48:03,461 - INFO - Data decoded successfully, length: 8490793
2025-02-27 23:48:03,461 - INFO - Attempting to parse JSON data
2025-02-27 23:48:03,624 - INFO - JSON parsed successfully. DataFrame shape: (7214, 56)
2025-02-27 23:48:03,708 - INFO - Data saved to received/received_data_20250227_234803.csv
2025-02-27 23:48:03,708 - INFO - Waiting for connection...
2025-02-27 23:55:22,385 - INFO - Starting receiving server...
2025-02-27 23:55:22,385 - INFO - Socket receive buffer size set to: 0.41 MB
2025-02-27 23:55:22,385 - ERROR - Server error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mohamed/Desktop/workstation/FL-CML-Pipeline/data/receiving_data.py", line 34, in start_server
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
2025-02-27 23:55:22,385 - INFO - Server socket closed
2025-02-27 23:55:23,410 - INFO - Got a connection from ('192.168.1.3', 33602)
2025-02-27 23:55:23,410 - INFO - Received 0.31MB in 1 chunks. Transfer rate: 3188.68MB/s
2025-02-27 23:55:23,410 - INFO - Received 0.37MB in 2 chunks. Transfer rate: 1582.23MB/s
2025-02-27 23:55:23,410 - INFO - Received 0.50MB in 3 chunks. Transfer rate: 1428.25MB/s
2025-02-27 23:55:23,410 - INFO - Received 0.69MB in 4 chunks. Transfer rate: 1416.98MB/s
2025-02-27 23:55:23,410 - INFO - Received 0.94MB in 5 chunks. Transfer rate: 1450.52MB/s
2025-02-27 23:55:23,412 - INFO - Connection closed. Received 2.77MB in 13 chunks. Average speed: 1541.58MB/s
2025-02-27 23:55:23,412 - INFO - Data decoded successfully, length: 2899941
2025-02-27 23:55:23,412 - INFO - Attempting to parse JSON data
2025-02-27 23:55:23,483 - INFO - JSON parsed successfully. DataFrame shape: (2452, 56)
2025-02-27 23:55:23,515 - INFO - Data saved to received/received_data_20250227_235523.csv
2025-02-27 23:55:23,515 - INFO - Waiting for connection...
